spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_pickup?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-wait: 10000
    max-active: 1000





  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 5000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0